name: parmed-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - pandas
  - nose
  - openmm
  - coverage
  - nose-timer
  - netCDF4
  - rdkit ==2020.09.4
  - nglview
  - ambertools
  - networkx
  - lxml
  - nose-timer
  - gromacs
