name: Tests

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: false
        python-version: ${{ matrix.python-version }}
        environment-file: devtools/environment-dev.yaml
        activate-environment: parmed-dev

    - name: Install and test
      shell: bash -l {0}
      run: python -m pip install . --no-deps

    - name: Environment Information
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: PyTest
      shell: bash -l {0}
      run: |
        pytest -rws -v --cov=codex --color=yes codex/
